/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by set-gen. DO NOT EDIT.

package sets

import (
	"reflect"
	"sort"

	api "kubepack.dev/module/pkg/api"
)

// sets.Matcher is a set of api.Matchers, implemented via map[api.Matcher]struct{} for minimal memory consumption.
type Matcher map[api.Matcher]Empty

// NewMatcher creates a Matcher from a list of values.
func NewMatcher(items ...api.Matcher) Matcher {
	ss := make(Matcher, len(items))
	ss.Insert(items...)
	return ss
}

// MatcherKeySet creates a Matcher from a keys of a map[api.Matcher](? extends interface{}).
// If the value passed in is not actually a map, this will panic.
func MatcherKeySet(theMap interface{}) Matcher {
	v := reflect.ValueOf(theMap)
	ret := Matcher{}

	for _, keyValue := range v.MapKeys() {
		ret.Insert(keyValue.Interface().(api.Matcher))
	}
	return ret
}

// Insert adds items to the set.
func (s Matcher) Insert(items ...api.Matcher) Matcher {
	for _, item := range items {
		s[item] = Empty{}
	}
	return s
}

// Delete removes all items from the set.
func (s Matcher) Delete(items ...api.Matcher) Matcher {
	for _, item := range items {
		delete(s, item)
	}
	return s
}

// Has returns true if and only if item is contained in the set.
func (s Matcher) Has(item api.Matcher) bool {
	_, contained := s[item]
	return contained
}

// HasAll returns true if and only if all items are contained in the set.
func (s Matcher) HasAll(items ...api.Matcher) bool {
	for _, item := range items {
		if !s.Has(item) {
			return false
		}
	}
	return true
}

// HasAny returns true if any items are contained in the set.
func (s Matcher) HasAny(items ...api.Matcher) bool {
	for _, item := range items {
		if s.Has(item) {
			return true
		}
	}
	return false
}

// Difference returns a set of objects that are not in s2
// For example:
// s1 = {a1, a2, a3}
// s2 = {a1, a2, a4, a5}
// s1.Difference(s2) = {a3}
// s2.Difference(s1) = {a4, a5}
func (s Matcher) Difference(s2 Matcher) Matcher {
	result := NewMatcher()
	for key := range s {
		if !s2.Has(key) {
			result.Insert(key)
		}
	}
	return result
}

// Union returns a new set which includes items in either s1 or s2.
// For example:
// s1 = {a1, a2}
// s2 = {a3, a4}
// s1.Union(s2) = {a1, a2, a3, a4}
// s2.Union(s1) = {a1, a2, a3, a4}
func (s1 Matcher) Union(s2 Matcher) Matcher {
	result := NewMatcher()
	for key := range s1 {
		result.Insert(key)
	}
	for key := range s2 {
		result.Insert(key)
	}
	return result
}

// Intersection returns a new set which includes the item in BOTH s1 and s2
// For example:
// s1 = {a1, a2}
// s2 = {a2, a3}
// s1.Intersection(s2) = {a2}
func (s1 Matcher) Intersection(s2 Matcher) Matcher {
	var walk, other Matcher
	result := NewMatcher()
	if s1.Len() < s2.Len() {
		walk = s1
		other = s2
	} else {
		walk = s2
		other = s1
	}
	for key := range walk {
		if other.Has(key) {
			result.Insert(key)
		}
	}
	return result
}

// IsSuperset returns true if and only if s1 is a superset of s2.
func (s1 Matcher) IsSuperset(s2 Matcher) bool {
	for item := range s2 {
		if !s1.Has(item) {
			return false
		}
	}
	return true
}

// Equal returns true if and only if s1 is equal (as a set) to s2.
// Two sets are equal if their membership is identical.
// (In practice, this means same elements, order doesn't matter)
func (s1 Matcher) Equal(s2 Matcher) bool {
	return len(s1) == len(s2) && s1.IsSuperset(s2)
}

type sortableSliceOfMatcher []api.Matcher

func (s sortableSliceOfMatcher) Len() int           { return len(s) }
func (s sortableSliceOfMatcher) Less(i, j int) bool { return lessMatcher(s[i], s[j]) }
func (s sortableSliceOfMatcher) Swap(i, j int)      { s[i], s[j] = s[j], s[i] }

// List returns the contents as a sorted api.Matcher slice.
func (s Matcher) List() []api.Matcher {
	res := make(sortableSliceOfMatcher, 0, len(s))
	for key := range s {
		res = append(res, key)
	}
	sort.Sort(res)
	return []api.Matcher(res)
}

// UnsortedList returns the slice with contents in random order.
func (s Matcher) UnsortedList() []api.Matcher {
	res := make([]api.Matcher, 0, len(s))
	for key := range s {
		res = append(res, key)
	}
	return res
}

// Returns a single element from the set.
func (s Matcher) PopAny() (api.Matcher, bool) {
	for key := range s {
		s.Delete(key)
		return key, true
	}
	var zeroValue api.Matcher
	return zeroValue, false
}

// Len returns the size of the set.
func (s Matcher) Len() int {
	return len(s)
}

func lessMatcher(lhs, rhs api.Matcher) bool {
	if lhs.Name < rhs.Name {
		return true
	}
	if lhs.Name > rhs.Name {
		return false
	}
	if lhs.Namespace < rhs.Namespace {
		return true
	}
	if lhs.Namespace > rhs.Namespace {
		return false
	}
	if lhs.Selector < rhs.Selector {
		return true
	}
	if lhs.Selector > rhs.Selector {
		return false
	}
	return false
}
