# permissions for end users to edit modules.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: module-editor-role
rules:
- apiGroups:
  - pkg.x-helm.dev
  resources:
  - modules
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - pkg.x-helm.dev
  resources:
  - modules/status
  verbs:
  - get
