# permissions for end users to edit moduleexecstatuses.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: moduleexecstatus-editor-role
rules:
- apiGroups:
  - pkg.x-helm.dev
  resources:
  - moduleexecstatuses
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - pkg.x-helm.dev
  resources:
  - moduleexecstatuses/status
  verbs:
  - get
