# permissions for end users to view moduleexecstatuses.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: moduleexecstatus-viewer-role
rules:
- apiGroups:
  - pkg.x-helm.dev
  resources:
  - moduleexecstatuses
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - pkg.x-helm.dev
  resources:
  - moduleexecstatuses/status
  verbs:
  - get
